In [1]:
import pickle 
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

In [2]:
from processing_data import *

In [3]:
with open('Tree_CT.pkl','rb') as f:
    pre= pickle.load(f)

In [4]:
pre

ColumnTransformer(remainder='passthrough',
                  transformers=[('OHE columns', OneHotEncoder(),
                                 ['BusinessTravel', 'Department',
                                  'MaritalStatus', 'EducationField', 'Gender',
                                  'JobRole']),
                                ('Label_encoder', OrdinalEncoder(),
                                 ['OverTime']),
                                ('Standard_scaler', StandardScaler(),
                                 ['Age', 'DailyRate', 'DistanceFromHome',
                                  'MonthlyRate', 'HourlyRate',
                                  'NumCompaniesWorked', 'TotalWorkingYears',
                                  'YearsAtCompany', 'YearsInCurrentRole',
                                  'YearsSinceLastPromotion',
                                  'PercentSalaryHike'])])

In [5]:
with open('Processed_data.pkl','rb') as f:
    df = pickle.load(f)

In [6]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,3,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,3,1,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,4,2,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,3,4,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,3,1,0,6,3,4,4,3,1,2

In [7]:
X = df.drop("Attrition",axis=1)
y =df["Attrition"].map({"No":0,"Yes":1})

In [8]:
df.Attrition.value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [9]:
x_train, x_test, y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=33)

In [10]:
processed_x_train = pre.fit_transform(x_train)

In [11]:
processed_x_train

array([[ 1.,  0.,  0., ...,  3.,  2.,  4.],
       [ 0.,  0.,  1., ...,  2.,  3.,  0.],
       [ 0.,  0.,  1., ...,  3.,  1.,  0.],
       ...,
       [ 0.,  1.,  0., ...,  2.,  3., 12.],
       [ 0.,  0.,  1., ...,  3.,  3.,  0.],
       [ 0.,  0.,  1., ...,  0.,  2.,  2.]])

In [12]:
processed_x_train[0]

array([ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  1.        , -0.3098615 ,  1.3622128 ,  1.16898078,
       -1.33034804,  0.05469197,  2.11675505, -0.30137951, -0.32177888,
       -0.60819028, -0.68968387, -0.5936842 ,  3.        ,  1.        ,
        4.        ,  2.        ,  4.        ,  3.        ,  2.        ,
        0.        ,  3.        ,  2.        ,  4.        ])

In [13]:
# model Building

In [14]:
import sklearn
sklearn.set_config(print_changed_only=False)

In [15]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(processed_x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=None, splitter='best')

In [16]:
#Prediction 
processed_x_test = pre.transform(x_test)
y_pred = dt.predict(processed_x_test)

In [17]:
# Evaluation
from sklearn.metrics import accuracy_score , precision_score, recall_score , f1_score , confusion_matrix , classification_report
acc = accuracy_score (y_test,y_pred)
print('Accuracy:',acc)
pr = precision_score (y_test,y_pred)
re = recall_score (y_test,y_pred)
f1 = f1_score (y_test,y_pred)
cm = confusion_matrix (y_test,y_pred)
print('Precisio:',pr,'\nRecall:',re,'\nF1:',f1,'\nConfusion Matrix:',cm)
print('Classification Report:\n',classification_report(y_test,y_pred))

Accuracy: 0.7663043478260869
Precisio: 0.3333333333333333
Recall: 0.3870967741935484
F1: 0.3582089552238806
Confusion Matrix: [[258  48]
 [ 38  24]]
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.84      0.86       306
           1       0.33      0.39      0.36        62

    accuracy                           0.77       368
   macro avg       0.60      0.62      0.61       368
weighted avg       0.78      0.77      0.77       368

In [18]:
results = pd.DataFrame(index=['Accuracy','F1'])
results['DT/imb']=[acc,f1]
results

            DT/imb
Accuracy  0.766304
F1        0.358209

In [19]:
#Prediction on training data -test of overfitting 
y_pred1=dt.predict(processed_x_train)

#Evaluation
from sklearn.metrics import accuracy_score , precision_score, recall_score , f1_score , confusion_matrix , classification_report
acc = accuracy_score (y_train,y_pred1)
print('Accuracy:',acc)
pr = precision_score (y_train,y_pred1)
re = recall_score (y_train,y_pred1)
f1 = f1_score (y_train,y_pred1)
cm = confusion_matrix (y_train,y_pred1)
print('Precisio:',pr,'\nRecall:',re,'\nF1:',f1,'\nConfusion Matrix:',cm)
print('Classification Report:\n',classification_report(y_train,y_pred1))

Accuracy: 1.0
Precisio: 1.0
Recall: 1.0
F1: 1.0
Confusion Matrix: [[927   0]
 [  0 175]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       927
           1       1.00      1.00      1.00       175

    accuracy                           1.00      1102
   macro avg       1.00      1.00      1.00      1102
weighted avg       1.00      1.00      1.00      1102

In [20]:
results['DT/Train']=[acc,f1]
results

            DT/imb  DT/Train
Accuracy  0.766304       1.0
F1        0.358209       1.0

In [21]:
##Data balancing and creating model
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)

dt_bal=DecisionTreeClassifier()
dt_bal.fit(x_smote,y_smote)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=None, splitter='best')

In [22]:
y_smote.value_counts()

Attrition
1    927
0    927
Name: count, dtype: int64

In [23]:
y_pred=dt_bal.predict(processed_x_test)

In [24]:
#Evaluation
from sklearn.metrics import accuracy_score , precision_score, recall_score , f1_score , confusion_matrix , classification_report
acc = accuracy_score (y_test,y_pred)
print('Accuracy:',acc)
pr = precision_score (y_test,y_pred)
re = recall_score (y_test,y_pred)
f1 = f1_score (y_test,y_pred)
cm = confusion_matrix (y_test,y_pred)
print('Precisio:',pr,'\nRecall:',re,'\nF1:',f1,'\nConfusion Matrix:',cm)
print('Classification Report:\n',classification_report(y_test,y_pred))

Accuracy: 0.7663043478260869
Precisio: 0.3235294117647059
Recall: 0.3548387096774194
F1: 0.3384615384615384
Confusion Matrix: [[260  46]
 [ 40  22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.85      0.86       306
           1       0.32      0.35      0.34        62

    accuracy                           0.77       368
   macro avg       0.60      0.60      0.60       368
weighted avg       0.78      0.77      0.77       368

In [25]:
results['DT/Smote']=[acc,f1]
results

            DT/imb  DT/Train  DT/Smote
Accuracy  0.766304       1.0  0.766304
F1        0.358209       1.0  0.338462

In [26]:
from sklearn.model_selection import GridSearchCV
#Creating dictionary
params={
    "criterion":("gini","entropy"),
    "splitter":("best","random"),
    "max_depth":(list(range(1,20,2))),
    "min_samples_split":[2,5,7,10,12,15],
    "min_samples_leaf":list(range(1,20)),}

tree_clf = DecisionTreeClassifier()
tree_cv = GridSearchCV(tree_clf,params,scoring="f1",n_jobs=-1,verbose=5,cv=5)

In [27]:
tree_cv.fit(processed_x_train,y_train)
best_params=tree_cv.best_params_
print(f"Best parameters: {best_params})")

Fitting 5 folds for each of 4560 candidates, totalling 22800 fits
Best parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_leaf': 14, 'min_samples_split': 5, 'splitter': 'best'})

In [28]:
tree_cv.best_params_

{'criterion': 'gini',
 'max_depth': 7,
 'min_samples_leaf': 14,
 'min_samples_split': 5,
 'splitter': 'best'}

In [29]:
#passing best parameter to the decision tree
dt_optimal=DecisionTreeClassifier(criterion='gini', max_depth=7, min_samples_leaf= 14,min_samples_split=7,splitter='best')
dt_optimal.fit(processed_x_train,y_train)

 
y_pred=dt_optimal.predict(processed_x_test)

dt_optimal=DecisionTreeClassifier(criterion='gini',max_depth=7,min_samples_leaf=14,min_samples_split=5,splitter='best')
dt_optimal.fit(processed_x_train,y_train)
y_pred=dt_optimal.predict(processed_x_test)
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8288043478260869
Precision: 0.48717948717948717
Recall Score: 0.3064516129032258
F1 Score 0.37623762376237624
Confusion Matrix:
 [[286  20]
 [ 43  19]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       306
           1       0.49      0.31      0.38        62

    accuracy                           0.83       368
   macro avg       0.68      0.62      0.64       368
weighted avg       0.80      0.83      0.81       368

In [30]:
results['DT/HPT']=[acc,f1]
results

            DT/imb  DT/Train  DT/Smote    DT/HPT
Accuracy  0.766304       1.0  0.766304  0.828804
F1        0.358209       1.0  0.338462  0.376238

In [31]:
#RANDOM FOREST IMPLEMENTATION

In [32]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
rf_clf.fit(processed_x_train,y_train)
y_pred=rf_clf.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8532608695652174
Precision: 0.8333333333333334
Recall Score: 0.16129032258064516
F1 Score 0.27027027027027023
Confusion Matrix:
 [[304   2]
 [ 52  10]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       306
           1       0.83      0.16      0.27        62

    accuracy                           0.85       368
   macro avg       0.84      0.58      0.59       368
weighted avg       0.85      0.85      0.81       368

In [33]:
rf_clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [34]:
results['RF'] =[acc,f1]
results

            DT/imb  DT/Train  DT/Smote    DT/HPT        RF
Accuracy  0.766304       1.0  0.766304  0.828804  0.853261
F1        0.358209       1.0  0.338462  0.376238  0.270270

In [35]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators=[int(x) for x in np.linspace(start=200,stop=200,num=5)]
max_features=['auto','sqrt','log2']
max_depth=[int(x)for x in np.linspace(10,110,num=5)]
max_depth.append(None)
min_samples_split=[5,7,10,13]
min_samples_leaf=[2,4]

random_grid={'n_estimators':n_estimators,'max_features':max_features,'max_depth':max_depth,'min_samples_split':min_samples_split,
             'min_samples_leaf':min_samples_leaf}
rf_clf1=RandomForestClassifier(random_state=42)

rf_cv = RandomizedSearchCV(estimator=rf_clf1,scoring='f1',param_distributions=random_grid,cv=3, verbose=2, n_jobs=-1)

In [36]:
np.linspace(200,2000,5)

array([ 200.,  650., 1100., 1550., 2000.])

In [37]:
rf_cv.fit(processed_x_train,y_train)
rf_best_params =rf_cv.best_params_
print(f"Best parameters:{rf_best_params}")

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters:{'n_estimators': 200, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 10}

In [38]:
rf_clf2 = RandomForestClassifier(n_estimators=200,min_samples_split=7,min_samples_leaf=2,max_features='sqrt',max_depth=10)
rf_clf2.fit(processed_x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=2,
                       min_samples_split=7, min_weight_fraction_leaf=0.0,
                       n_estimators=200, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [39]:
y_pred=rf_clf2.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8478260869565217
Precision: 0.8
Recall Score: 0.12903225806451613
F1 Score 0.2222222222222222
Confusion Matrix:
 [[304   2]
 [ 54   8]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.92       306
           1       0.80      0.13      0.22        62

    accuracy                           0.85       368
   macro avg       0.82      0.56      0.57       368
weighted avg       0.84      0.85      0.80       368

In [40]:
results['RF/HPT']=[acc,f1]
results

            DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT
Accuracy  0.766304       1.0  0.766304  0.828804  0.853261  0.847826
F1        0.358209       1.0  0.338462  0.376238  0.270270  0.222222

In [41]:
#BAGGGING

In [42]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

KNN=KNeighborsClassifier()
LR=LogisticRegression()

model_bagg=BaggingClassifier(estimator=KNN,n_estimators=2)

model_bagg.fit(processed_x_train,y_train)
y_pred=model_bagg.predict(processed_x_test)

In [43]:
acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.842391304347826
Precision: 0.75
Recall Score: 0.0967741935483871
F1 Score 0.1714285714285714
Confusion Matrix:
 [[304   2]
 [ 56   6]]
              precision    recall  f1-score   support

           0       0.84      0.99      0.91       306
           1       0.75      0.10      0.17        62

    accuracy                           0.84       368
   macro avg       0.80      0.55      0.54       368
weighted avg       0.83      0.84      0.79       368

In [44]:
results['Bag/KNN']=[acc,f1]
results

            DT/imb  DT/Train  DT/Smote    DT/HPT        RF    RF/HPT   Bag/KNN
Accuracy  0.766304       1.0  0.766304  0.828804  0.853261  0.847826  0.842391
F1        0.358209       1.0  0.338462  0.376238  0.270270  0.222222  0.171429

In [45]:
model_bagg

BaggingClassifier(base_estimator='deprecated', bootstrap=True,
                  bootstrap_features=False,
                  estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                                 metric='minkowski',
                                                 metric_params=None,
                                                 n_jobs=None, n_neighbors=5,
                                                 p=2, weights='uniform'),
                  max_features=1.0, max_samples=1.0, n_estimators=2,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [46]:
model_bagg=BaggingClassifier(estimator=LR,n_estimators=50)

model_bagg.fit(processed_x_train,y_train)
y_pred=model_bagg.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8614130434782609
Precision: 0.6170212765957447
Recall Score: 0.46774193548387094
F1 Score 0.5321100917431193
Confusion Matrix:
 [[288  18]
 [ 33  29]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       306
           1       0.62      0.47      0.53        62

    accuracy                           0.86       368
   macro avg       0.76      0.70      0.73       368
weighted avg       0.85      0.86      0.85       368

In [47]:
results['Bag/LR/smpl']=[acc,f1]
results

,DT/imb,DT/Train,DT/Smote,DT/HPT,RF,RF/HPT,Bag/KNN,Bag/LR/smpl
Accuracy,0.766304,1.0,0.766304,0.828804,0.853261,0.847826,0.842391,0.861413
F1,0.358209,1.0,0.338462,0.376238,0.270270,0.222222,0.171429,0.532110

In [48]:
# BOOSTING AND XG BOOSTING

In [49]:
from sklearn.ensemble import GradientBoostingClassifier
gbm=GradientBoostingClassifier()
gbm.fit(processed_x_train,y_train)

y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.875
Precision: 0.7666666666666667
Recall Score: 0.3709677419354839
F1 Score 0.5
Confusion Matrix:
 [[299   7]
 [ 39  23]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.77      0.37      0.50        62

    accuracy                           0.88       368
   macro avg       0.83      0.67      0.71       368
weighted avg       0.86      0.88      0.86       368

In [50]:
gbm

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [51]:
results['GB']=[acc,f1]
results

,DT/imb,DT/Train,DT/Smote,DT/HPT,RF,RF/HPT,Bag/KNN,Bag/LR/smpl,GB
Accuracy,0.766304,1.0,0.766304,0.828804,0.853261,0.847826,0.842391,0.861413,0.875
F1,0.358209,1.0,0.338462,0.376238,0.270270,0.222222,0.171429,0.532110,0.500

In [52]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'learning_rate':[0.01,0.03,0.06,0.1,0.4,0.5,0.6,0.7],
    'max_depth':[5,6,7,8,9,10],
    'n_estimators':[50,65,80,100]
}
GB=GradientBoostingClassifier()

rcv= RandomizedSearchCV(estimator=GB , scoring='f1',refit=True,param_distributions=param_grid,cv=5,verbose=2,n_jobs=-1)

rcv.fit(processed_x_train,y_train)
rcv.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

{'n_estimators': 65, 'max_depth': 9, 'learning_rate': 0.6}

In [53]:
GB2=GradientBoostingClassifier(n_estimators=100,max_depth=7,learning_rate=0.4)
y_pred=gbm.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.875
Precision: 0.7666666666666667
Recall Score: 0.3709677419354839
F1 Score 0.5
Confusion Matrix:
 [[299   7]
 [ 39  23]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.77      0.37      0.50        62

    accuracy                           0.88       368
   macro avg       0.83      0.67      0.71       368
weighted avg       0.86      0.88      0.86       368

In [54]:
results['GB/HPT']=[acc,f1]
results

,DT/imb,DT/Train,DT/Smote,DT/HPT,RF,RF/HPT,Bag/KNN,Bag/LR/smpl,GB,GB/HPT
Accuracy,0.766304,1.0,0.766304,0.828804,0.853261,0.847826,0.842391,0.861413,0.875,0.875
F1,0.358209,1.0,0.338462,0.376238,0.270270,0.222222,0.171429,0.532110,0.500,0.500

In [55]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(processed_x_train,y_train)

y_pred=LR.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.8668478260869565
Precision: 0.6444444444444445
Recall Score: 0.46774193548387094
F1 Score 0.5420560747663551
Confusion Matrix:
 [[290  16]
 [ 33  29]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       306
           1       0.64      0.47      0.54        62

    accuracy                           0.87       368
   macro avg       0.77      0.71      0.73       368
weighted avg       0.86      0.87      0.86       368

In [57]:
results['LR']=[acc,f1]
results

,DT/imb,DT/Train,DT/Smote,DT/HPT,RF,RF/HPT,Bag/KNN,Bag/LR/smpl,GB,GB/HPT,LR
Accuracy,0.766304,1.0,0.766304,0.828804,0.853261,0.847826,0.842391,0.861413,0.875,0.875,0.755435
F1,0.358209,1.0,0.338462,0.376238,0.270270,0.222222,0.171429,0.532110,0.500,0.500,0.521277

In [58]:
from imblearn.over_sampling import SMOTE
x_smote,y_smote = SMOTE().fit_resample(processed_x_train,y_train)
LR.fit(x_smote,y_smote)

y_pred=LR.predict(processed_x_test)

acc = accuracy_score(y_test,y_pred)
pr = precision_score(y_test,y_pred)
re = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print('Accuracy Score: ',acc,'\nPrecision:', pr,'\nRecall Score:', re,'\nF1 Score', f1, '\nConfusion Matrix: \n', cm)
print(classification_report(y_test,y_pred))

Accuracy Score:  0.75
Precision: 0.3828125
Recall Score: 0.7903225806451613
F1 Score 0.5157894736842106
Confusion Matrix:
 [[227  79]
 [ 13  49]]
              precision    recall  f1-score   support

           0       0.95      0.74      0.83       306
           1       0.38      0.79      0.52        62

    accuracy                           0.75       368
   macro avg       0.66      0.77      0.67       368
weighted avg       0.85      0.75      0.78       368